
services:
  backend: #Servicio para el backend con Django
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on: #No se inicia hasta que se inicia la base de datos PostgreSQL
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    ports:
      - "8000:8000"
    restart: always #En caso de frenarse el container, se reinicia

  frontend: #Servicio para el frontend con React
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend #No se inicia hasta que se inicie el backend
    restart: always #En caso de frenarse el container, se reinicia

  db:
    image: postgres:12.0-alpine
    container_name: database
    env_file: ./.env.postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
  static:
  media: