
name: CI/CD Pipeline
#El evento se va a ejecutar cada vez que se modifica el archivo
on:
  push:
    paths:
      - 'Prueba3-CICD/index.html'
jobs:
  #Etapa 1 - Subida de la imágen a docker hub y buildeo de la misma
  build:
    runs-on: ubuntu-latest
    steps:
    #Obtiene el código del repo
    - name: Obtención del código
      uses: actions/checkout@v4
    #Configura Docker Buildx
    - name: Configuración de Docker Buildx
      uses: docker/setup-buildx-action@v2
    #Logeo a DockerHub
    - name: Login a DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    # Buildea y pushea la imágen Docker.
    - name: Build y push a Docker-Hub
      uses: docker/build-push-action@v3
      with:
        context: ./Prueba3-CICD
        file: ./Prueba3-CICD/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/nginx:latest

  #Etapa 2 - Deploy de la imagen en el servidor
  deploy:
      runs-on: ubuntu-latest
      needs: build #Depende de la etapa anterior
      container:
        image: docker/compose:1.29.2 ##Imagen con docker pre instalado

      steps:
        #Obtiene el código del repo
      - name: Checkout code
        uses: actions/checkout@v2
        #Realiza el deploy
      - name: Deploy usando docker-compose
        run: |
          docker-compose down
          docker-compose up -d